name: Usernotes
version: 1.0.0
main: com.rteenagers.parrot.Usernotes
api-version: "1.16"
description: Fetches sheets for in-game use

commands:
  points:
    description: Usernotes lookup command
    usage: "/points [user]"
  point:
    description: Adds usernote
    usage: "/point [ban/mute/warnban/warnmute] [user] [amount] [reason]"
  removepoint:
    description: Removes a usernote from the database
    usage: "/removepoint [ban/mute] [id]"
    aliases: [pointremove]
  pointlookup:
    description: View a specific note
    usage: "/pointlookup [ban/mute] [id]"
    aliases: [lookuppoint]

permissions:
  points.edit:
    description: Allows users to add or remove points
    default: op
  points.lookup.all:
    description: Allows users to search up anyones points
    default: op
  points.lookup.self:
    description: Allows users to search up their own points
    default: true

