name: Usernotes
version: 1.3.0
main: com.rteenagers.parrot.Usernotes
api-version: "1.17"
description: Manages usernotes database for in-game use

commands:
  points:
    description: Usernotes lookup command
    usage: "/points [user]"
  point:
    description: Adds usernote
    usage: "/point [ban/mute/ipban] [user] [amount] [reason]"
    aliases: [addpoint, pointadd, ap]
  removepoint:
    description: Removes a usernote from the database
    usage: "/removepoint [ban/mute] [id]"
    aliases: [pointremove, rp]
  pointlookup:
    description: View a specific note
    usage: "/pointlookup [ban/mute] [id]"
    aliases: [lookuppoint]
  pointlist:
    description: View a list of all notes
    usage: "/pointlist"
    aliases: [listpoints]
  resetpoints:
    description: Resets database
    usage: "/resetpoints confirm"

permissions:
  points.edit:
    description: Allows users to add or remove points
    default: op
  points.lookup:
    description: Allows users to search up anyones points
    default: op
  points.lookup.self:
    description: Allows users to search up their own points
    default: true
  points.admin:
    description: Allows users to reset the database
    default: op

