name: Usernotes
version: 0.1.1
main: com.rteenagers.parrot.Usernotes
api-version: "1.16"
description: Fetches sheets for in-game use

commands:
  points:
    description: Usernotes lookup command
    usage: "/points [user]"
  point:
    description: Adds usernote
    usage: "/point [ban/mute/warnban/warnmute] [user] [amount] [reason]"
  removepoint:
    description: Removes a usernote from the database
    usage: "/point [ban/mute] [id]"