name: Usernotes
version: 0.1.5
main: com.rteenagers.parrot.Usernotes
api-version: "1.16"
description: Fetches sheets for in-game use

commands:
  points:
    description: Usernotes lookup command
    usage: "/points [user]"
  point:
    description: Adds usernote
    usage: "/point [ban/mute/warnban/warnmute] [user] [amount] [reason]"
  removepoint:
    description: Removes a usernote from the database
    usage: "/removepoint [ban/mute] [id]"
    aliases: [pointremove]
  pointlookup:
    description: View a specific note
    usage: "/pointlookup [ban/mute] [id]"
    aliases: [lookuppoint]
  banleaderboard:
    description: View who has the most bans
    usage: /banleaderboard

permissions:
  points.edit:
    description: Allows users to add or remove points
    default: op
  points.lookup:
    description: Allows users to search up anyones points
    default: op
  points.leaderboard:
    description: Allows users to see the points leaderboard
    default: op

