name: Parrot
version: 0.0.2
main: com.rteenagers.parrot.Parrot
api-version: "1.16"
description: Fetches sheets for in-game use

commands:
  notes:
    description: test command
    usage: "/notes [player]"